### ISSUE TITLE
How to skip statements/functions?

### ISSUE THREAD

**Issue by dtinth** [douglasduteil/isparta#24] opened 2015-03-05 10:14 UTC
This function is only called when there is an error (it displays an error dialog on web page). It is not useful to test the coverage of this function.
 
![screen shot 2015-03-05 at 17 11 26](https://cloud.githubusercontent.com/assets/193136/6502940/c2f94720-c35a-11e4-8619-b835d62b27d5.png)

In Istanbul, you could use `/* istanbul skip next */`, but it doesn't work in Isparta. I also tried `/* isparta ignore next */` without success.

**Comment by bassettsj** [comment] 2015-03-17 19:37
Having the same problem. Would be great to allow the same [Ignoring Code For Coverage Spec](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md) for isparta.

**Comment by kentcdodds** [comment] 2015-06-12 22:00
I'm also experiencing the same issue. @bassettsj, if I'm not mistaken, it's not that isparta needs an "Ignoring Code For Coverage Spec" because it actually uses istanbul behind the scenes. I think this is simply a bug in isparta that somehow istanbul isn't seeing those comment annotations... Is that right @douglasduteil?

**Comment by pawelbrzezinski** [comment] 2015-06-22 08:27
Same here.

**Comment by t128** [comment] 2015-06-24 11:48
+1

**Comment by kentcdodds** [comment] 2015-06-24 12:01
@douglasduteil, if you have any idea what the issue might be and where it could potentially be solved and perhaps give some direction on making a PR, I would be happy to contribute a PR.

**Comment by andrewzey** [comment] 2015-07-08 18:18
+1. This is quite problematic. I'll see if I can contribute a fix for this soon.

**Comment by t128** [comment] 2015-07-08 18:22
$ 10 added
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=9221471)](https://www.bountysource.com/issues/9221471-how-to-skip-statements-functions?utm_source=9221471&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by kentcdodds** [comment] 2015-07-08 18:29
$100 added :-)

**Comment by andrewzey** [comment] 2015-07-08 18:30
Wow ok. I'll give this a shot today.

**Comment by amitev** [comment] 2015-07-23 05:36
Any progress with this?

**Comment by douglasduteil** [comment] 2015-07-23 07:35
Hum sorry guys but I prefer investing my time in merging with Istanbul #31

**Comment by t128** [comment] 2015-07-23 08:33
hmm, is there a way to transfer a bounty to another issue?

**Comment by amitev** [comment] 2015-08-31 09:49
Any news on that. Looks like the merging with Instanbul doesn't go smoothly...

**Comment by kentcdodds** [comment] 2015-09-06 04:00
Another $100 added. I would totally accept this (and prefer it) if the merger with Istanbul is successful.

**Comment by chaseadamsio** [comment] 2015-10-08 01:25
Based on the commit history continuing to grow and the last comment on #31 was over 2 months ago, is it safe to assume this issue could still be resolved in the `isparta` project?

I did some investigating today and it seems like the problem is that `babel` transforms the code and the AST it produces is not being correctly parsed by `istanbul`.

**Closed** 2015-10-31 15:54 UTC

**Comment by kentcdodds** [comment] 2015-10-31 16:05
Fantastic news! I'll award the contributor my bounty when I get a chance to test this out on Monday. This is awesome!

**Comment by douglasduteil** [comment] 2015-10-31 16:18
@kentcdodds Keep me posted on this. 
 I currently have no test project to really test this out

**Comment by taion** [comment] 2015-10-31 16:43
For an example, compare:

Without pragmas: https://coveralls.io/builds/4009011/source?filename=modules%2FRoute.js
With pragmas: https://coveralls.io/builds/4009276/source?filename=modules%2FRoute.js

**Comment by taion** [comment] 2015-10-31 16:47
There is (of course) a caveat here - something like `istanbul ignore next` for a method on an ES6 class will only work if you're using loose mode. Otherwise Babel transpiles the code in such a way that the pragma comment no longer references the method.

**Comment by kentcdodds** [comment] 2015-10-31 17:32
@TheMcMurder, if you're not doing anything this weekend and want to bump our code coverage big time, you might try upgrading isparta and seeing if this works for us :-)

**Comment by TheMcMurder** [comment] 2015-11-02 16:43
Tested it in out project. Works great.

**Comment by kentcdodds** [comment] 2015-11-02 16:52
@taion, please claim the bounty here: https://www.bountysource.com/issues/9221471-how-to-skip-statements-functions I'll then be able to award you the $200 that I've placed on this issue. Thanks!

**Comment by amitev** [comment] 2015-11-07 21:29
Which version of isparta should I use in order to get the /* istanbul ignore next */ working?

**Comment by taion** [comment] 2015-11-07 21:35
Looks like v3.2.0 or later.

**Comment by amitev** [comment] 2015-11-07 22:00
I ask because I'm using 3.5.3 and it doesn't work.

**Comment by taion** [comment] 2015-11-07 22:11
Check your transpiled code - this isn't doing anything beyond plumbing everything through. If Babel moves your comment somewhere away from the block you want to ignore, then nothing's going to happen.

This is most relevant for something like method declarations in ES6 classes - you'll need to use `"loose": "all"` there.

**Comment by amitev** [comment] 2015-11-08 09:59
That worked. Thank you very much!
